/***********************************************************************
  Jose Gabriel Valenzuela CSC110AB 31269, May 2nd 2019 Module 7 Arrays
 
 The Ship class receives 3 ints and 1 boolean, randomly generated by
 ShipShinkingGame class. This class uses those data points to create a
 random ship that will be places on the Sea class 2-D array.
 
 ***********************************************************************/
public class Ship {
   
   //declares variables
	private int row;
	private int col;
	private boolean horizontalOrVertical;
	private int s;
	private String id;
	private static char idValue = 'A';
	private int hitCount;
	private int missCount;
	private int hits;
	private boolean isShipDestroyed;

	// creates Ship Constructor
	public Ship(int r, int c, boolean orientation, int size) {
		
      // Randomly selects ship's size based on a 20%,30% and 50% rate
      if (size == 1 || size == 2) {
			s = 2;
		} else if (size == 3 || size == 4 || size == 5) {
			s = 3;
		} else {
			s = 4;
		}

		// Sets random cordinates
		row = r;
		col = c;

		horizontalOrVertical = orientation;
		idValue++;
		hitCount = 0;
		hits = hitCount;

	}
   //get method that returns the orientation (vertical = false & horizontal = true)
	public boolean getOrientation() {

		return horizontalOrVertical;
	}
   //get method returns ship size
	public int getSize() {

		return s;
	}
   //get method returns  row
	public int getRow() {

		return row;
	}
   //get method returns column
	public int getColumn() {

		return col;
	}
   //Method attemept at checking for destroyed ship
	public void getDestroyed() {

		if (hits == s) {
			System.out.print("        Congrats! A ship was destroyed");

		}

	}
   //toString method that returns the ship's idvalue
	public String toString() {
		id = "" + idValue;

		return "" + id;
	}

}
